// Chaque élément : emoji affiché, nom prononcé, catégorie, et pour les animaux
// un cri (onomatopée lue par la synthèse vocale si aucun fichier audio n'existe
// dans le dossier sounds/<id>.mp3).
const ITEMS = [
  // --- Animaux ---
  { id: "chien",      emoji: "🐶", nom: "le chien",       cat: "animal", cri: "Ouaf ouaf !" },
  { id: "chat",       emoji: "🐱", nom: "le chat",        cat: "animal", cri: "Miaou !" },
  { id: "vache",      emoji: "🐮", nom: "la vache",       cat: "animal", cri: "Meuh !" },
  { id: "cochon",     emoji: "🐷", nom: "le cochon",      cat: "animal", cri: "Groin groin !" },
  { id: "mouton",     emoji: "🐑", nom: "le mouton",      cat: "animal", cri: "Bêêê !" },
  { id: "chevre",     emoji: "🐐", nom: "la chèvre",      cat: "animal", cri: "Bêêê !" },
  { id: "cheval",     emoji: "🐴", nom: "le cheval",      cat: "animal", cri: "Hiiii !" },
  { id: "poule",      emoji: "🐔", nom: "la poule",       cat: "animal", cri: "Cot cot codet !" },
  { id: "coq",        emoji: "🐓", nom: "le coq",         cat: "animal", cri: "Cocorico !" },
  { id: "poussin",    emoji: "🐥", nom: "le poussin",     cat: "animal", cri: "Piou piou !" },
  { id: "canard",     emoji: "🦆", nom: "le canard",      cat: "animal", cri: "Coin coin !" },
  { id: "oiseau",     emoji: "🐦", nom: "l'oiseau",       cat: "animal", cri: "Cui cui !" },
  { id: "hibou",      emoji: "🦉", nom: "le hibou",       cat: "animal", cri: "Hou hou !" },
  { id: "lion",       emoji: "🦁", nom: "le lion",        cat: "animal", cri: "Rooaaar !" },
  { id: "tigre",      emoji: "🐯", nom: "le tigre",       cat: "animal", cri: "Grrrr !" },
  { id: "ours",       emoji: "🐻", nom: "l'ours",         cat: "animal", cri: "Grrr !" },
  { id: "loup",       emoji: "🐺", nom: "le loup",        cat: "animal", cri: "Aouuuuh !" },
  { id: "elephant",   emoji: "🐘", nom: "l'éléphant",     cat: "animal", cri: "Toooot !" },
  { id: "singe",      emoji: "🐵", nom: "le singe",       cat: "animal", cri: "Ou ou ou, ah ah ah !" },
  { id: "grenouille", emoji: "🐸", nom: "la grenouille",  cat: "animal", cri: "Coa coa !" },
  { id: "serpent",    emoji: "🐍", nom: "le serpent",     cat: "animal", cri: "Sssssss !" },
  { id: "abeille",    emoji: "🐝", nom: "l'abeille",      cat: "animal", cri: "Bzzzzz !" },
  { id: "souris",     emoji: "🐭", nom: "la souris",      cat: "animal", cri: "Hiii hiii !" },
  { id: "lapin",      emoji: "🐰", nom: "le lapin",       cat: "animal", cri: "" },
  { id: "girafe",     emoji: "🦒", nom: "la girafe",      cat: "animal", cri: "" },
  { id: "tortue",     emoji: "🐢", nom: "la tortue",      cat: "animal", cri: "" },
  { id: "poisson",    emoji: "🐟", nom: "le poisson",     cat: "animal", cri: "Blub blub !" },
  { id: "papillon",   emoji: "🦋", nom: "le papillon",    cat: "animal", cri: "" },
  { id: "pingouin",   emoji: "🐧", nom: "le pingouin",    cat: "animal", cri: "" },

  // --- Véhicules ---
  { id: "voiture",     emoji: "🚗", nom: "la voiture",            cat: "vehicule" },
  { id: "camion",      emoji: "🚚", nom: "le camion",             cat: "vehicule" },
  { id: "bus",         emoji: "🚌", nom: "le bus",                cat: "vehicule" },
  { id: "train",       emoji: "🚂", nom: "le train",              cat: "vehicule" },
  { id: "avion",       emoji: "✈️", nom: "l'avion",               cat: "vehicule" },
  { id: "helico",      emoji: "🚁", nom: "l'hélicoptère",         cat: "vehicule" },
  { id: "bateau",      emoji: "⛵", nom: "le bateau",             cat: "vehicule" },
  { id: "velo",        emoji: "🚲", nom: "le vélo",               cat: "vehicule" },
  { id: "moto",        emoji: "🏍️", nom: "la moto",               cat: "vehicule" },
  { id: "tracteur",    emoji: "🚜", nom: "le tracteur",           cat: "vehicule" },
  { id: "fusee",       emoji: "🚀", nom: "la fusée",              cat: "vehicule" },
  { id: "ambulance",   emoji: "🚑", nom: "l'ambulance",           cat: "vehicule" },
  { id: "pompiers",    emoji: "🚒", nom: "le camion de pompiers", cat: "vehicule" },
  { id: "police",      emoji: "🚓", nom: "la voiture de police",  cat: "vehicule" },
  { id: "taxi",        emoji: "🚕", nom: "le taxi",               cat: "vehicule" },
  { id: "trottinette", emoji: "🛴", nom: "la trottinette",        cat: "vehicule" },

  // --- Objets du quotidien ---
  { id: "chaise",     emoji: "🪑", nom: "la chaise",          cat: "objet" },
  { id: "lit",        emoji: "🛏️", nom: "le lit",             cat: "objet" },
  { id: "cuillere",   emoji: "🥄", nom: "la cuillère",        cat: "objet" },
  { id: "fourchette", emoji: "🍴", nom: "la fourchette",      cat: "objet" },
  { id: "verre",      emoji: "🥛", nom: "le verre",           cat: "objet" },
  { id: "tasse",      emoji: "☕", nom: "la tasse",           cat: "objet" },
  { id: "assiette",   emoji: "🍽️", nom: "l'assiette",         cat: "objet" },
  { id: "cle",        emoji: "🔑", nom: "la clé",             cat: "objet" },
  { id: "livre",      emoji: "📖", nom: "le livre",           cat: "objet" },
  { id: "ballon",     emoji: "⚽", nom: "le ballon",          cat: "objet" },
  { id: "chaussure",  emoji: "👟", nom: "la chaussure",       cat: "objet" },
  { id: "chapeau",    emoji: "🧢", nom: "le chapeau",         cat: "objet" },
  { id: "brosse",     emoji: "🪥", nom: "la brosse à dents",  cat: "objet" },
  { id: "savon",      emoji: "🧼", nom: "le savon",           cat: "objet" },
  { id: "parapluie",  emoji: "☂️", nom: "le parapluie",       cat: "objet" },
  { id: "lampe",      emoji: "💡", nom: "la lampe",           cat: "objet" },
  { id: "telephone",  emoji: "📱", nom: "le téléphone",       cat: "objet" },
  { id: "horloge",    emoji: "⏰", nom: "le réveil",          cat: "objet" },
  { id: "lunettes",   emoji: "👓", nom: "les lunettes",       cat: "objet" },
  { id: "sac",        emoji: "🎒", nom: "le sac à dos",       cat: "objet" },
  { id: "crayon",     emoji: "✏️", nom: "le crayon",          cat: "objet" },
  { id: "ciseaux",    emoji: "✂️", nom: "les ciseaux",        cat: "objet" },
  { id: "bain",       emoji: "🛁", nom: "la baignoire",       cat: "objet" },
  { id: "doudou",     emoji: "🧸", nom: "le doudou",          cat: "objet" },
  { id: "porte",      emoji: "🚪", nom: "la porte",           cat: "objet" },
  { id: "tshirt",     emoji: "👕", nom: "le tee-shirt",       cat: "objet" },
  { id: "pantalon",   emoji: "👖", nom: "le pantalon",        cat: "objet" },
  { id: "chaussettes",emoji: "🧦", nom: "les chaussettes",    cat: "objet" },
];
